// 国家区号列表 - 美国在第一位，其余按英文首字母排序
// 已排除：阿富汗、伊朗、朝鲜、叙利亚
// value 使用 code-en 格式作为唯一标识，避免美国和加拿大等相同区号国家混淆
export const phoneCodeOptions = [
  { code: '1', country: '美国', en: 'United States', value: '1-United States' },
  // A
  { code: '355', country: '阿尔巴尼亚', en: 'Albania', value: '355-Albania' },
  { code: '213', country: '阿尔及利亚', en: 'Algeria', value: '213-Algeria' },
  { code: '1684', country: '美属萨摩亚', en: 'American Samoa', value: '1684-American Samoa' },
  { code: '376', country: '安道尔共和国', en: 'Andorra', value: '376-Andorra' },
  { code: '244', country: '安哥拉', en: 'Angola', value: '244-Angola' },
  { code: '1264', country: '安圭拉岛', en: 'Anguilla', value: '1264-Anguilla' },
  { code: '1268', country: '安提瓜和巴布达', en: 'Antigua and Barbuda', value: '1268-Antigua and Barbuda' },
  { code: '54', country: '阿根廷', en: 'Argentina', value: '54-Argentina' },
  { code: '374', country: '亚美尼亚', en: 'Armenia', value: '374-Armenia' },
  { code: '297', country: '阿鲁巴', en: 'Aruba', value: '297-Aruba' },
  { code: '61', country: '澳大利亚', en: 'Australia', value: '61-Australia' },
  { code: '43', country: '奥地利', en: 'Austria', value: '43-Austria' },
  { code: '994', country: '阿塞拜疆', en: 'Azerbaijan', value: '994-Azerbaijan' },
  // B
  { code: '1242', country: '巴哈马', en: 'Bahamas', value: '1242-Bahamas' },
  { code: '973', country: '巴林', en: 'Bahrain', value: '973-Bahrain' },
  { code: '880', country: '孟加拉国', en: 'Bangladesh', value: '880-Bangladesh' },
  { code: '1246', country: '巴巴多斯', en: 'Barbados', value: '1246-Barbados' },
  { code: '375', country: '白俄罗斯', en: 'Belarus', value: '375-Belarus' },
  { code: '32', country: '比利时', en: 'Belgium', value: '32-Belgium' },
  { code: '501', country: '伯利兹', en: 'Belize', value: '501-Belize' },
  { code: '229', country: '贝宁', en: 'Benin', value: '229-Benin' },
  { code: '1441', country: '百慕大', en: 'Bermuda', value: '1441-Bermuda' },
  { code: '975', country: '不丹', en: 'Bhutan', value: '975-Bhutan' },
  { code: '591', country: '玻利维亚', en: 'Bolivia', value: '591-Bolivia' },
  { code: '387', country: '波黑', en: 'Bosnia and Herzegovina', value: '387-Bosnia and Herzegovina' },
  { code: '267', country: '博茨瓦纳', en: 'Botswana', value: '267-Botswana' },
  { code: '55', country: '巴西', en: 'Brazil', value: '55-Brazil' },
  { code: '673', country: '文莱', en: 'Brunei', value: '673-Brunei' },
  { code: '359', country: '保加利亚', en: 'Bulgaria', value: '359-Bulgaria' },
  { code: '226', country: '布基纳法索', en: 'Burkina Faso', value: '226-Burkina Faso' },
  { code: '257', country: '布隆迪', en: 'Burundi', value: '257-Burundi' },
  // C
  { code: '855', country: '柬埔寨', en: 'Cambodia', value: '855-Cambodia' },
  { code: '237', country: '喀麦隆', en: 'Cameroon', value: '237-Cameroon' },
  { code: '1', country: '加拿大', en: 'Canada', value: '1-Canada' },
  { code: '238', country: '佛得角', en: 'Cape Verde', value: '238-Cape Verde' },
  { code: '1345', country: '开曼群岛', en: 'Cayman Islands', value: '1345-Cayman Islands' },
  { code: '236', country: '中非共和国', en: 'Central African Republic', value: '236-Central African Republic' },
  { code: '235', country: '乍得', en: 'Chad', value: '235-Chad' },
  { code: '56', country: '智利', en: 'Chile', value: '56-Chile' },
  { code: '86', country: '中国', en: 'China', value: '86-China' },
  { code: '57', country: '哥伦比亚', en: 'Colombia', value: '57-Colombia' },
  { code: '269', country: '科摩罗', en: 'Comoros', value: '269-Comoros' },
  { code: '242', country: '刚果(布)', en: 'Congo', value: '242-Congo' },
  { code: '243', country: '刚果(金)', en: 'Congo (DRC)', value: '243-Congo (DRC)' },
  { code: '682', country: '库克群岛', en: 'Cook Islands', value: '682-Cook Islands' },
  { code: '506', country: '哥斯达黎加', en: 'Costa Rica', value: '506-Costa Rica' },
  { code: '225', country: '科特迪瓦', en: 'Côte d\'Ivoire', value: '225-Côte d\'Ivoire' },
  { code: '385', country: '克罗地亚', en: 'Croatia', value: '385-Croatia' },
  { code: '53', country: '古巴', en: 'Cuba', value: '53-Cuba' },
  { code: '599', country: '库拉索', en: 'Curaçao', value: '599-Curaçao' },
  { code: '357', country: '塞浦路斯', en: 'Cyprus', value: '357-Cyprus' },
  { code: '420', country: '捷克', en: 'Czech Republic', value: '420-Czech Republic' },
  // D
  { code: '45', country: '丹麦', en: 'Denmark', value: '45-Denmark' },
  { code: '253', country: '吉布提', en: 'Djibouti', value: '253-Djibouti' },
  { code: '1767', country: '多米尼克', en: 'Dominica', value: '1767-Dominica' },
  { code: '1809', country: '多米尼加共和国', en: 'Dominican Republic', value: '1809-Dominican Republic' },
  // E
  { code: '593', country: '厄瓜多尔', en: 'Ecuador', value: '593-Ecuador' },
  { code: '20', country: '埃及', en: 'Egypt', value: '20-Egypt' },
  { code: '503', country: '萨尔瓦多', en: 'El Salvador', value: '503-El Salvador' },
  { code: '240', country: '赤道几内亚', en: 'Equatorial Guinea', value: '240-Equatorial Guinea' },
  { code: '291', country: '厄立特里亚', en: 'Eritrea', value: '291-Eritrea' },
  { code: '372', country: '爱沙尼亚', en: 'Estonia', value: '372-Estonia' },
  { code: '268', country: '斯威士兰', en: 'Eswatini', value: '268-Eswatini' },
  { code: '251', country: '埃塞俄比亚', en: 'Ethiopia', value: '251-Ethiopia' },
  // F
  { code: '500', country: '福克兰群岛', en: 'Falkland Islands', value: '500-Falkland Islands' },
  { code: '298', country: '法罗群岛', en: 'Faroe Islands', value: '298-Faroe Islands' },
  { code: '679', country: '斐济', en: 'Fiji', value: '679-Fiji' },
  { code: '358', country: '芬兰', en: 'Finland', value: '358-Finland' },
  { code: '33', country: '法国', en: 'France', value: '33-France' },
  { code: '594', country: '法属圭亚那', en: 'French Guiana', value: '594-French Guiana' },
  { code: '689', country: '法属波利尼西亚', en: 'French Polynesia', value: '689-French Polynesia' },
  // G
  { code: '241', country: '加蓬', en: 'Gabon', value: '241-Gabon' },
  { code: '220', country: '冈比亚', en: 'Gambia', value: '220-Gambia' },
  { code: '995', country: '格鲁吉亚', en: 'Georgia', value: '995-Georgia' },
  { code: '49', country: '德国', en: 'Germany', value: '49-Germany' },
  { code: '233', country: '加纳', en: 'Ghana', value: '233-Ghana' },
  { code: '350', country: '直布罗陀', en: 'Gibraltar', value: '350-Gibraltar' },
  { code: '30', country: '希腊', en: 'Greece', value: '30-Greece' },
  { code: '299', country: '格陵兰', en: 'Greenland', value: '299-Greenland' },
  { code: '1473', country: '格林纳达', en: 'Grenada', value: '1473-Grenada' },
  { code: '590', country: '瓜德罗普', en: 'Guadeloupe', value: '590-Guadeloupe' },
  { code: '1671', country: '关岛', en: 'Guam', value: '1671-Guam' },
  { code: '502', country: '危地马拉', en: 'Guatemala', value: '502-Guatemala' },
  { code: '224', country: '几内亚', en: 'Guinea', value: '224-Guinea' },
  { code: '245', country: '几内亚比绍', en: 'Guinea-Bissau', value: '245-Guinea-Bissau' },
  { code: '592', country: '圭亚那', en: 'Guyana', value: '592-Guyana' },
  // H
  { code: '509', country: '海地', en: 'Haiti', value: '509-Haiti' },
  { code: '504', country: '洪都拉斯', en: 'Honduras', value: '504-Honduras' },
  { code: '852', country: '中国香港', en: 'Hong Kong', value: '852-Hong Kong' },
  { code: '36', country: '匈牙利', en: 'Hungary', value: '36-Hungary' },
  // I
  { code: '354', country: '冰岛', en: 'Iceland', value: '354-Iceland' },
  { code: '91', country: '印度', en: 'India', value: '91-India' },
  { code: '62', country: '印度尼西亚', en: 'Indonesia', value: '62-Indonesia' },
  { code: '964', country: '伊拉克', en: 'Iraq', value: '964-Iraq' },
  { code: '353', country: '爱尔兰', en: 'Ireland', value: '353-Ireland' },
  { code: '972', country: '以色列', en: 'Israel', value: '972-Israel' },
  { code: '39', country: '意大利', en: 'Italy', value: '39-Italy' },
  // J
  { code: '1876', country: '牙买加', en: 'Jamaica', value: '1876-Jamaica' },
  { code: '81', country: '日本', en: 'Japan', value: '81-Japan' },
  { code: '962', country: '约旦', en: 'Jordan', value: '962-Jordan' },
  // K
  { code: '7', country: '哈萨克斯坦', en: 'Kazakhstan', value: '7-Kazakhstan' },
  { code: '254', country: '肯尼亚', en: 'Kenya', value: '254-Kenya' },
  { code: '686', country: '基里巴斯', en: 'Kiribati', value: '686-Kiribati' },
  { code: '965', country: '科威特', en: 'Kuwait', value: '965-Kuwait' },
  { code: '996', country: '吉尔吉斯斯坦', en: 'Kyrgyzstan', value: '996-Kyrgyzstan' },
  // L
  { code: '856', country: '老挝', en: 'Laos', value: '856-Laos' },
  { code: '371', country: '拉脱维亚', en: 'Latvia', value: '371-Latvia' },
  { code: '961', country: '黎巴嫩', en: 'Lebanon', value: '961-Lebanon' },
  { code: '266', country: '莱索托', en: 'Lesotho', value: '266-Lesotho' },
  { code: '231', country: '利比里亚', en: 'Liberia', value: '231-Liberia' },
  { code: '218', country: '利比亚', en: 'Libya', value: '218-Libya' },
  { code: '423', country: '列支敦士登', en: 'Liechtenstein', value: '423-Liechtenstein' },
  { code: '370', country: '立陶宛', en: 'Lithuania', value: '370-Lithuania' },
  { code: '352', country: '卢森堡', en: 'Luxembourg', value: '352-Luxembourg' },
  // M
  { code: '853', country: '中国澳门', en: 'Macau', value: '853-Macau' },
  { code: '261', country: '马达加斯加', en: 'Madagascar', value: '261-Madagascar' },
  { code: '265', country: '马拉维', en: 'Malawi', value: '265-Malawi' },
  { code: '60', country: '马来西亚', en: 'Malaysia', value: '60-Malaysia' },
  { code: '960', country: '马尔代夫', en: 'Maldives', value: '960-Maldives' },
  { code: '223', country: '马里', en: 'Mali', value: '223-Mali' },
  { code: '356', country: '马耳他', en: 'Malta', value: '356-Malta' },
  { code: '692', country: '马绍尔群岛', en: 'Marshall Islands', value: '692-Marshall Islands' },
  { code: '596', country: '马提尼克', en: 'Martinique', value: '596-Martinique' },
  { code: '222', country: '毛里塔尼亚', en: 'Mauritania', value: '222-Mauritania' },
  { code: '230', country: '毛里求斯', en: 'Mauritius', value: '230-Mauritius' },
  { code: '262', country: '马约特', en: 'Mayotte', value: '262-Mayotte' },
  { code: '52', country: '墨西哥', en: 'Mexico', value: '52-Mexico' },
  { code: '691', country: '密克罗尼西亚', en: 'Micronesia', value: '691-Micronesia' },
  { code: '373', country: '摩尔多瓦', en: 'Moldova', value: '373-Moldova' },
  { code: '377', country: '摩纳哥', en: 'Monaco', value: '377-Monaco' },
  { code: '976', country: '蒙古', en: 'Mongolia', value: '976-Mongolia' },
  { code: '382', country: '黑山', en: 'Montenegro', value: '382-Montenegro' },
  { code: '1664', country: '蒙特塞拉特', en: 'Montserrat', value: '1664-Montserrat' },
  { code: '212', country: '摩洛哥', en: 'Morocco', value: '212-Morocco' },
  { code: '258', country: '莫桑比克', en: 'Mozambique', value: '258-Mozambique' },
  { code: '95', country: '缅甸', en: 'Myanmar', value: '95-Myanmar' },
  // N
  { code: '264', country: '纳米比亚', en: 'Namibia', value: '264-Namibia' },
  { code: '674', country: '瑙鲁', en: 'Nauru', value: '674-Nauru' },
  { code: '977', country: '尼泊尔', en: 'Nepal', value: '977-Nepal' },
  { code: '31', country: '荷兰', en: 'Netherlands', value: '31-Netherlands' },
  { code: '687', country: '新喀里多尼亚', en: 'New Caledonia', value: '687-New Caledonia' },
  { code: '64', country: '新西兰', en: 'New Zealand', value: '64-New Zealand' },
  { code: '505', country: '尼加拉瓜', en: 'Nicaragua', value: '505-Nicaragua' },
  { code: '227', country: '尼日尔', en: 'Niger', value: '227-Niger' },
  { code: '234', country: '尼日利亚', en: 'Nigeria', value: '234-Nigeria' },
  { code: '683', country: '纽埃', en: 'Niue', value: '683-Niue' },
  { code: '672', country: '诺福克岛', en: 'Norfolk Island', value: '672-Norfolk Island' },
  { code: '389', country: '北马其顿', en: 'North Macedonia', value: '389-North Macedonia' },
  { code: '1670', country: '北马里亚纳群岛', en: 'Northern Mariana Islands', value: '1670-Northern Mariana Islands' },
  { code: '47', country: '挪威', en: 'Norway', value: '47-Norway' },
  // O
  { code: '968', country: '阿曼', en: 'Oman', value: '968-Oman' },
  // P
  { code: '92', country: '巴基斯坦', en: 'Pakistan', value: '92-Pakistan' },
  { code: '680', country: '帕劳', en: 'Palau', value: '680-Palau' },
  { code: '970', country: '巴勒斯坦', en: 'Palestine', value: '970-Palestine' },
  { code: '507', country: '巴拿马', en: 'Panama', value: '507-Panama' },
  { code: '675', country: '巴布亚新几内亚', en: 'Papua New Guinea', value: '675-Papua New Guinea' },
  { code: '595', country: '巴拉圭', en: 'Paraguay', value: '595-Paraguay' },
  { code: '51', country: '秘鲁', en: 'Peru', value: '51-Peru' },
  { code: '63', country: '菲律宾', en: 'Philippines', value: '63-Philippines' },
  { code: '48', country: '波兰', en: 'Poland', value: '48-Poland' },
  { code: '351', country: '葡萄牙', en: 'Portugal', value: '351-Portugal' },
  { code: '1787', country: '波多黎各', en: 'Puerto Rico', value: '1787-Puerto Rico' },
  // Q
  { code: '974', country: '卡塔尔', en: 'Qatar', value: '974-Qatar' },
  // R
  { code: '262', country: '留尼汪', en: 'Réunion', value: '262-Réunion' },
  { code: '40', country: '罗马尼亚', en: 'Romania', value: '40-Romania' },
  { code: '7', country: '俄罗斯', en: 'Russia', value: '7-Russia' },
  { code: '250', country: '卢旺达', en: 'Rwanda', value: '250-Rwanda' },
  // S
  { code: '290', country: '圣赫勒拿', en: 'Saint Helena', value: '290-Saint Helena' },
  { code: '1869', country: '圣基茨和尼维斯', en: 'Saint Kitts and Nevis', value: '1869-Saint Kitts and Nevis' },
  { code: '1758', country: '圣卢西亚', en: 'Saint Lucia', value: '1758-Saint Lucia' },
  { code: '508', country: '圣皮埃尔和密克隆', en: 'Saint Pierre and Miquelon', value: '508-Saint Pierre and Miquelon' },
  { code: '1784', country: '圣文森特和格林纳丁斯', en: 'Saint Vincent and the Grenadines', value: '1784-Saint Vincent and the Grenadines' },
  { code: '685', country: '萨摩亚', en: 'Samoa', value: '685-Samoa' },
  { code: '378', country: '圣马力诺', en: 'San Marino', value: '378-San Marino' },
  { code: '239', country: '圣多美和普林西比', en: 'São Tomé and Príncipe', value: '239-São Tomé and Príncipe' },
  { code: '966', country: '沙特阿拉伯', en: 'Saudi Arabia', value: '966-Saudi Arabia' },
  { code: '221', country: '塞内加尔', en: 'Senegal', value: '221-Senegal' },
  { code: '381', country: '塞尔维亚', en: 'Serbia', value: '381-Serbia' },
  { code: '248', country: '塞舌尔', en: 'Seychelles', value: '248-Seychelles' },
  { code: '232', country: '塞拉利昂', en: 'Sierra Leone', value: '232-Sierra Leone' },
  { code: '65', country: '新加坡', en: 'Singapore', value: '65-Singapore' },
  { code: '1721', country: '荷属圣马丁', en: 'Sint Maarten', value: '1721-Sint Maarten' },
  { code: '421', country: '斯洛伐克', en: 'Slovakia', value: '421-Slovakia' },
  { code: '386', country: '斯洛文尼亚', en: 'Slovenia', value: '386-Slovenia' },
  { code: '677', country: '所罗门群岛', en: 'Solomon Islands', value: '677-Solomon Islands' },
  { code: '252', country: '索马里', en: 'Somalia', value: '252-Somalia' },
  { code: '27', country: '南非', en: 'South Africa', value: '27-South Africa' },
  { code: '82', country: '韩国', en: 'South Korea', value: '82-South Korea' },
  { code: '211', country: '南苏丹', en: 'South Sudan', value: '211-South Sudan' },
  { code: '34', country: '西班牙', en: 'Spain', value: '34-Spain' },
  { code: '94', country: '斯里兰卡', en: 'Sri Lanka', value: '94-Sri Lanka' },
  { code: '249', country: '苏丹', en: 'Sudan', value: '249-Sudan' },
  { code: '597', country: '苏里南', en: 'Suriname', value: '597-Suriname' },
  { code: '46', country: '瑞典', en: 'Sweden', value: '46-Sweden' },
  { code: '41', country: '瑞士', en: 'Switzerland', value: '41-Switzerland' },
  // T
  { code: '886', country: '中国台湾', en: 'Taiwan', value: '886-Taiwan' },
  { code: '992', country: '塔吉克斯坦', en: 'Tajikistan', value: '992-Tajikistan' },
  { code: '255', country: '坦桑尼亚', en: 'Tanzania', value: '255-Tanzania' },
  { code: '66', country: '泰国', en: 'Thailand', value: '66-Thailand' },
  { code: '670', country: '东帝汶', en: 'Timor-Leste', value: '670-Timor-Leste' },
  { code: '228', country: '多哥', en: 'Togo', value: '228-Togo' },
  { code: '690', country: '托克劳', en: 'Tokelau', value: '690-Tokelau' },
  { code: '676', country: '汤加', en: 'Tonga', value: '676-Tonga' },
  { code: '1868', country: '特立尼达和多巴哥', en: 'Trinidad and Tobago', value: '1868-Trinidad and Tobago' },
  { code: '216', country: '突尼斯', en: 'Tunisia', value: '216-Tunisia' },
  { code: '90', country: '土耳其', en: 'Turkey', value: '90-Turkey' },
  { code: '993', country: '土库曼斯坦', en: 'Turkmenistan', value: '993-Turkmenistan' },
  { code: '1649', country: '特克斯和凯科斯群岛', en: 'Turks and Caicos Islands', value: '1649-Turks and Caicos Islands' },
  { code: '688', country: '图瓦卢', en: 'Tuvalu', value: '688-Tuvalu' },
  // U
  { code: '256', country: '乌干达', en: 'Uganda', value: '256-Uganda' },
  { code: '380', country: '乌克兰', en: 'Ukraine', value: '380-Ukraine' },
  { code: '971', country: '阿联酋', en: 'United Arab Emirates', value: '971-United Arab Emirates' },
  { code: '44', country: '英国', en: 'United Kingdom', value: '44-United Kingdom' },
  { code: '598', country: '乌拉圭', en: 'Uruguay', value: '598-Uruguay' },
  { code: '998', country: '乌兹别克斯坦', en: 'Uzbekistan', value: '998-Uzbekistan' },
  // V
  { code: '678', country: '瓦努阿图', en: 'Vanuatu', value: '678-Vanuatu' },
  { code: '379', country: '梵蒂冈', en: 'Vatican City', value: '379-Vatican City' },
  { code: '58', country: '委内瑞拉', en: 'Venezuela', value: '58-Venezuela' },
  { code: '84', country: '越南', en: 'Vietnam', value: '84-Vietnam' },
  { code: '1284', country: '英属维尔京群岛', en: 'Virgin Islands (British)', value: '1284-Virgin Islands (British)' },
  { code: '1340', country: '美属维尔京群岛', en: 'Virgin Islands (U.S.)', value: '1340-Virgin Islands (U.S.)' },
  // W
  { code: '681', country: '瓦利斯和富图纳', en: 'Wallis and Futuna', value: '681-Wallis and Futuna' },
  // Y
  { code: '967', country: '也门', en: 'Yemen', value: '967-Yemen' },
  // Z
  { code: '260', country: '赞比亚', en: 'Zambia', value: '260-Zambia' },
  { code: '263', country: '津巴布韦', en: 'Zimbabwe', value: '263-Zimbabwe' }
]

// 手机区号搜索过滤函数
export const filterPhoneCodeOption = (input, option) => {
  const item = phoneCodeOptions.find(p => p.value === option.value)
  if (!item) return false
  const searchText = input.toLowerCase()
  return item.code.includes(searchText) ||
         item.country.includes(searchText) ||
         item.en.toLowerCase().includes(searchText)
}

// 根据 value 获取区号 code
export const getPhoneCode = (value) => {
  if (!value) return ''
  return value.split('-')[0]
}

// 根据 value 获取国家信息
export const getPhoneCountry = (value) => {
  const item = phoneCodeOptions.find(p => p.value === value)
  return item || null
}
